### ISSUE TITLE
Java port

### ISSUE THREAD

**Issue by Serg-Norseman** [Serg-Norseman/GEDKeeperJ#2]
I started porting the GEDKeeper program on July 14th. From that day, I started preparing the C# source code for Java development features. And since July, 24th there was actually a code conversion.

As of today, porting itself is completed.
There are a lot of shortcomings, problems and bugs in different parts of the program, at different levels: UI, components, kernel.

However, despite some success, there are doubts that the right way is chosen.

**Comment by Serg-Norseman** [comment]
Java application, which opened 5 of my working databases (GEDCOM-files, a total of 3.8 MB on the disk) took 402 MB of RAM. A freshly-launched application immediately takes 100 mb.

The .NET application, the old one, takes 24 MB at startup. The same 5 open files - the program took in memory 70 mb.

I'm breaking from such a comparison ...

**Comment by KarenArzumanyan** [comment]
What was the reason for porting?
I tried to compile the GEDKeeperJ project now, it seems that it works. Visually at the level of the old project GEDKeeper.

**Comment by Serg-Norseman** [comment]
The reasons for starting porting were to achieve a greater, maximum cross-platform program. The experiment with porting to Eto ended in failure - bringing most of the program blocks to the working state, it became clear that part of the visual series and functional will be lost. Not all are significant, but it is unpleasant to lose existing opportunities.

Of course, that using Eto / Xwt / Avalonia we can get a cross-platform application that works at least on Win / Linux / Mac. But when you use any of these frameworks - part of the functionality is inevitably lost. Because all these frameworks are built on the principle of the least common multiple. And in the case of the port to Eto, I believe that the result is ugly.

When creating the port in Java, consciously and deliberately efforts were made to restore the existing functional and interface. Because to create a new one, it is necessary that the old work in full.

In principle, this Java port is quite successful, there are rest a few features that need to be restored to start moving forward for the development of the program. And I know that almost everything is possible. Just with some features it was difficult to humble.

**Comment by Serg-Norseman** [comment]
Personally for me, the most important is getting programs on the platforms of Win / Linux / Android. Still there are a couple of people who want to get a Mac version, but this platform is not available to me.

When creating a cross-platform GK, I did not want to re-create the Linux interface on GTK #. But the use of cross-platform frameworks for C # actually failed. The only way to use them for me is to greatly simplify the GUI in the direction of current trends. Elementary on Xwt and Avalonia does not even have a toolbar.

**Comment by Serg-Norseman** [comment]
Most likely, the port in Java will continue to live and develop further. I doubt that I will give up such a wealth of choice and variety of options for development. Just need to get used to and overcome some conservatism ...

**Comment by Serg-Norseman** [comment]
Although there remains an important point in the deploy of the application to users, and what part of them will be lost due to the inability to use modern versions of the JRE

**Comment by ruslangaripov** [comment]
> the decision to port it was taken abruptly, impulsively and under the influence of emotions.

No, I think the decision was born when it had to appear. It wasn't an accidental one. It looks like C#-coded project has one direction: build enhanced functionality **but** without good (if any) support of any platform except Microsoft Windows. Practice of @Serg-Norseman has shown poor abilities of WinForms to support non-Windows systems (Microsoft itself currently doesn't apply any efforts there; other developers just has no good solution).
