### ISSUE TITLE
Restore the work of a progression with long processes, asynchronously, tasks

### ISSUE THREAD

**Issue by Serg-Norseman** [Serg-Norseman/GEDKeeperJ#25]

**Comment by Serg-Norseman** [comment]
The introduction of SwingWorker and related things, has led to the fact that the data collection for tips is now skipping - at the moment of calling this function the database has not been loaded yet. Those. need a way to wait ...

**Comment by ruslangaripov** [comment]
Therefore, to not to lock the main window while the "message of the day" 
window waits on database loading, the window `days tips' must be owned by a 
separate, non-main, GUI thread?

Yours truly,
Ruslan Garipov <ruslanngaripov at gmail dot com>.
----------------------------------------------
MinGW-w64 developer, with write after approval
GEDKeeper collaborator

**Comment by Serg-Norseman** [comment]
I do not know. This is my weak topic, which I do not understand well ... :(

**Comment by ruslangaripov** [comment]
Or once the main window got a signal from the working thread (one that 
loads a database), it shows an additional window with the "day tips" 
collected from the loaded database? I believe I have overcomplicated the 
problem proposing to create a dedicated GUI thread for the "Day tips" 
window, sorry ☻

Yours truly,
Ruslan Garipov <ruslanngaripov at gmail dot com>.
----------------------------------------------
MinGW-w64 developer, with write after approval
GEDKeeper collaborator

**Comment by Serg-Norseman** [comment]
I tried to implement the examples from the textbooks SwingWorker with the function of waiting for completion - nothing works at all. I tried to implement a progression based on ProgressMonitor - it did not work either. I do not have any basic understanding :(

**Comment by Serg-Norseman** [comment]
I think that some java-expert with experience and knowledge of nuances is needed.

**Comment by Serg-Norseman** [comment]
The project is completely closed.
